### ISSUE TITLE
great idea

### ISSUE THREAD

**Issue by avriltank** [symplely/zend-ffi#1]
thanks for your project

**Comment by TheTechsTech** [comment]
Appreciated, there is one thing that needs checking and feedback/PR is Linux issues as things currently stand. Since at the moment my focus is on Windows behaviors.

There is certain hurlers that is thread specific I need to figure out before moving on to a Linux box.

**Comment by TheTechsTech** [comment]
I am pausing on getting native **PThreads** working with FFI, needs a lot more investigation and more likely C development of PHP source code. Seems someone else has started something similar https://github.com/mrsuh/php-pthreads. 

Currently this project is stable for my current needs, tests done on Linux, Mac and Windows - PHP 74 to 8.2 and a release published.
